InvoiceAutomation/Models/Invoice.cs
using Newtonsoft.Json;

namespace InvoiceAutomation.Models
{
    public class Invoice
    {
        [JsonProperty("Id")]
        public int? Id { get; set; }
        [JsonProperty("Invoice_Number")]
        public string? Invoice_Number { get; set; }
        [JsonProperty("Document_Number")]
        public string? Document_Number { get; set; }
        [JsonProperty("Data_Of_Creation")]
        public DateTime Data_Of_Creation { get; set; }
        [JsonProperty("Sender_Code")]
        public string? Sender_Code { get; set; }
        [JsonProperty("Recipient_Code")]
        public string? Recipient_Code { get; set; }
        [JsonProperty("Cost_Code")]
        public string? Cost_Code { get; set; }
        [JsonProperty("Name")]
        public string? Name { get; set; }
        [JsonProperty("Item_Number")]
        public string? Item_Number { get; set; }
        [JsonProperty("Unit")]
        public string? Unit { get; set; }
        [JsonProperty("Quantity")]
        public int? Quantity { get; set; }
        [JsonProperty("Price")]
        public float? Price { get; set; }
        [JsonProperty("Allowed")]
        public string? Allowed { get; set; }
        [JsonProperty("Controller")]
        public string? Controller { get; set; }
        [JsonProperty("Passed")]
        public string? Passed { get; set; }
        [JsonProperty("Accepted")]
        public string? Accepted { get; set; }
    }
}

InvoiceAutomation/Controllers/InvoiceController.cs
using InvoiceAutomation.EF;
using InvoiceAutomation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;
using Xceed.Document.NET;
using Xceed.Words.NET;

namespace InvoiceAutomation.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly ApplicationDbContext _db;

        protected readonly DbSet<Invoice> _dbSet;

        public List<Invoice> ListOfProducts = new List<Invoice>();

        public InvoiceController(ApplicationDbContext applicationDbContext)
        {
            _db = applicationDbContext;
            _dbSet = _db.Set<Invoice>();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DownloadInvoice([FromBody] List<Invoice> invoiceList)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                using (DocX doc = DocX.Create(stream))
                {
                    string[] columnHeaders1 = { "№ Документа", "Дата", "Шифр отправителя", "Шифр получателя" };
                    string[] columnHeaders2 = { "№", "Шифр затрат", "Наименование", "Номенклатурный номер", "Ед. изм", "Кол-во", "Цена", "Сумма" };
                    string[] columnHeaders3 = { "Разрешил", "Контролёр", "Сдал", "Принял" };

                    float[] columnWidths1 = { 88.3881f, 138.5f, 138.5f, 191.233499f };
                    float[] columnWidths2 = { 22.6636f, 65.7245328f, 138.5f, 138.5f, 33.995448f, 32.578971f, 62.32954f, 62.32954f };
                    float[] columnWidths3 = { 88.3881f, 138.5f, 138.5f, 191.233499f };

                    Paragraph title = doc.InsertParagraph();
                    title.Append("Накладная на внутреннее перемещение").FontSize(16).Alignment = Alignment.center;

                    Paragraph invoiceNumber = doc.InsertParagraph();
                    invoiceNumber.Append(invoiceList[0].Invoice_Number).FontSize(15).Alignment = Alignment.center;

                    Table table1 = doc.AddTable(1, 4);
                    table1.Alignment = Alignment.center;

                    table1.Design = TableDesign.TableGrid;


                    for (int i = 0; i < columnHeaders1.Length; i++)
                    {
                        table1.Rows[0].Cells[i].Paragraphs.First().Append(columnHeaders1[i]).Bold().Alignment = Alignment.center;
                        table1.SetColumnWidth(i, columnWidths1[i]);
                    }
                    Row row1 = table1.InsertRow();

                    // Заполнение ячеек данными из объекта InvoiceItem
                    row1.Cells[0].Paragraphs.First().Append(invoiceList[0].Document_Number.ToString());
                    row1.Cells[1].Paragraphs.First().Append(invoiceList[0].Data_Of_Creation.Date.ToString("dd.MM.yyyy"));
                    row1.Cells[2].Paragraphs.First().Append(invoiceList[0].Sender_Code);
                    row1.Cells[3].Paragraphs.First().Append(invoiceList[0].Recipient_Code);

                    doc.InsertTable(table1);

                    doc.InsertParagraph();
                    //Вторая таблица


                    Table table2 = doc.AddTable(1, 8);

                    table2.Alignment = Alignment.center;

                    table2.Design = TableDesign.TableGrid;

                    for (int i = 0; i < columnHeaders2.Length; i++)
                    {
                        table2.Rows[0].Cells[i].Paragraphs.First().Append(columnHeaders2[i]).Bold().Alignment = Alignment.center;
                        table2.SetColumnWidth(i, columnWidths2[i]);
                    }

                    var serialNumber = 0;
                    // Добавление данных из базы данных в таблицу
                    foreach (var item in invoiceList)
                    {
                        // Создание новой строки в таблице
                        Row row2 = table2.InsertRow();

                        serialNumber++;

                        var sum = item.Quantity * item.Price;
                        // Заполнение ячеек данными из объекта InvoiceItem
                        row2.Cells[0].Paragraphs.First().Append(serialNumber.ToString());
                        row2.Cells[1].Paragraphs.First().Append(item.Cost_Code.ToString());
                        row2.Cells[2].Paragraphs.First().Append(item.Name);
                        row2.Cells[3].Paragraphs.First().Append(item.Item_Number);
                        row2.Cells[4].Paragraphs.First().Append(item.Unit);
                        row2.Cells[5].Paragraphs.First().Append(item.Quantity.ToString());
                        row2.Cells[6].Paragraphs.First().Append(item.Price.ToString());
                        row2.Cells[7].Paragraphs.First().Append(sum.ToString());
                    }

                    doc.InsertTable(table2);

                    doc.InsertParagraph();

                    //Третья таблица
                    Table table3 = doc.AddTable(1, 4);
                    table3.Alignment = Alignment.center;

                    table3.Design = TableDesign.TableGrid;


                    for (int i = 0; i < columnHeaders3.Length; i++)
                    {
                        table3.Rows[0].Cells[i].Paragraphs.First().Append(columnHeaders3[i]).Bold().Alignment = Alignment.center;
                        table3.SetColumnWidth(i, columnWidths3[i]);
                    }
                    Row row3 = table3.InsertRow();

                    // Заполнение ячеек данными из объекта InvoiceItem
                    row3.Cells[0].Paragraphs.First().Append(invoiceList[0].Allowed.ToString());
                    row3.Cells[1].Paragraphs.First().Append(invoiceList[0].Controller.ToString());
                    row3.Cells[2].Paragraphs.First().Append(invoiceList[0].Passed.ToString());
                    row3.Cells[3].Paragraphs.First().Append(invoiceList[0].Accepted.ToString());

                    doc.InsertTable(table3);

                    doc.Save();
                }

                stream.Seek(0, SeekOrigin.Begin);

                // Устанавливаем имя файла, которое будет отображаться у клиента
                string fileName = "example.docx";

                // Отправляем файл клиенту
                return File(stream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            }

        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var result = await _dbSet.AsNoTracking().GroupBy(x => x.Invoice_Number).Select(group => group.First()).ToListAsync();

            return View("List", result);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string Invoice_Number)
        {
            var result = await _dbSet.AsNoTracking().Where(i => i.Invoice_Number == Invoice_Number).ToListAsync();

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> AddPrice(string Invoice_Number)
        {
            var result = await _dbSet.AsNoTracking().Where(i => i.Invoice_Number == Invoice_Number).ToListAsync();

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> AddPriceInvoice([FromBody] PriceUpdateModel model)
        {
            try
            {
                var result = await _dbSet.FindAsync(new object[] { model.Id });

                result.Price = float.Parse(model.Price);

                _dbSet.Update(result);

                await _db.SaveChangesAsync();
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Search(string Invoice_Number)
        {
            if (Invoice_Number is null)
            {
                var resultNULL = await _dbSet.AsNoTracking().GroupBy(x => x.Invoice_Number).Select(group => group.First()).ToListAsync();

                return View("List", resultNULL);
            }
            else
            {
                var result = await _dbSet
        .AsNoTracking()
        .Where(i => i.Invoice_Number.Contains(Invoice_Number) || i.Name.Contains(Invoice_Number) || i.Item_Number.Contains(Invoice_Number)) // Фильтрация по Invoice_Number и/или Name
        .GroupBy(x => x.Invoice_Number)
        .Select(group => group.First())
        .ToListAsync();
                return View("List", result);
            }
        }



        [HttpGet]
        public async Task<IActionResult> Delete(string Invoice_Number)
        {
            var result = await _dbSet.AsNoTracking().Where(i => i.Invoice_Number == Invoice_Number).ToListAsync();

            _dbSet.RemoveRange(result);

            await _db.SaveChangesAsync();

            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateInvoice([FromBody] List<Invoice> invoiceList)
        {
            if (invoiceList.Count == 0)
            {
                return BadRequest();
            }
            try
            {
                foreach (var invoice in invoiceList)
                {
                    await _dbSet.AddAsync(invoice);
                }

                await _db.SaveChangesAsync();

                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        //[HttpGet]
        //public async Task<IActionResult> List(string sortBy)
        //{
        //    var result = await _dbSet.AsNoTracking().GroupBy(x => x.Invoice_Number).Select(group => group.First()).ToListAsync();

        //    if (sortBy == "Date")
        //    {

InvoiceAutomation/Views/Invoice/AddPrice.cshtml
@using Newtonsoft.Json;
@model IEnumerable<InvoiceAutomation.Models.Invoice>

@{
    ViewData["Title"] = "GetAllAsync";
}

<style>

    /* Устанавливаем стили для всей страницы */
    body {
        font-family: Arial, sans-serif; /* Шрифт для всего текста */
        margin: 0; /* Убираем отступы на странице */
        padding: 0; /* Убираем внутренние отступы на странице */
    }

    /* Устанавливаем стили для заголовка h1 */
    h2 {
        text-align: center; /* Выравниваем заголовок по центру */
    }

    /* Устанавливаем стили для таблицы */
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        background-color: #fff;
        table-layout: fixed; /* Фиксируем ширину столбцов */
    }

    /* Устанавливаем стили для заголовков таблицы (th) */
    th {
        background-color: #f0f0f0;
        padding: 10px;
        text-align: left;
        white-space: nowrap; /* Запрещаем перенос текста в заголовках */
        font-weight: bold;
    }

    /* Устанавливаем стили для ячеек таблицы (td) */
    td {
        padding: 10px;
        text-align: left;
        white-space: nowrap; /* Запрещаем перенос текста в ячейках */
        overflow: hidden; /* Скрываем содержимое, которое не помещается */
        text-overflow: ellipsis; /* Добавляем многоточие для обрезанного текста */
    }

    /* Устанавливаем стили для строк таблицы (tr) */
    tr:nth-child(even) {
        background-color: #f2f2f2; /* Цвет фона четных строк */
    }

    /* Устанавливаем стили для строк таблицы при наведении курсора */
    tr:hover {
        background-color: #ddd; /* Цвет фона строки при наведении курсора */
    }

    /* Устанавливаем стили для ссылок в ячейках таблицы */
    a {
        text-decoration: none; /* Убираем подчеркивание для ссылок */
        color: #007bff; /* Цвет ссылок */
    }

        /* Устанавливаем стили для ссылок в ячейках таблицы при наведении курсора */
        a:hover {
            text-decoration: underline; /* Подчеркиваем ссылки при наведении курсора */
        }

    h3 {
        text-align: center;
        font-weight: normal;
    }

</style>
    <h3>Накладная на внутреннее перемещение</h3>
    @{
        var invoice_Number = Model.FirstOrDefault();
        <h3>@Html.DisplayFor(modelItem => invoice_Number.Invoice_Number)</h3>
    }

    <table class="data-grid">
        <thead>
            <tr>
                <th>
                    <label>Номер документа</label>
                </th>
                <th>
                    <label>Дата</label>
                </th>
                <th>
                    <label>Шифр отправителя</label>
                </th>
                <th>
                    <label>Шифр получателя</label>
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var firstItem = Model.FirstOrDefault();
                if (firstItem != null)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => firstItem.Document_Number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => firstItem.Data_Of_Creation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => firstItem.Sender_Code)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => firstItem.Recipient_Code)
                        </td>
                    </tr>
                }
            }
        </tbody>

    </table>

    <table class="data-grid">
        <thead>
            <tr>
                <th>
                    <label>Шифр затрат</label>
                </th>
                <th>
                    <label>Наименование</label>
                </th>
                <th>
                    <label>Номенклатурный номер</label>
                </th>
                <th>
                    <label>Ед. изм</label>
                </th>
                <th>
                    <label>Количество</label>
                </th>
                <th>
                    <label>Цена</label>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost_Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Item_Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Unit)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                    <input type="text" name="Price[@Model.ToList().IndexOf(item)]" placeholder="Введите цену" />
                    </td>
                    <td>
                    <button class="save-button" data-row-index="@Model.ToList().IndexOf(item)" data-item-id="@item.Id">Сохранить</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <table class="data-grid">
        <thead>
            <tr>
                <th>
                    <label>Разрешил</label>
                </th>
                <th>
                    <label>Контроллёр</label>
                </th>
                <th>
                    <label>Сдал</label>
                </th>
                <th>
                    <label>Принял</label>
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                var secondItem = Model.FirstOrDefault();
                if (secondItem != null)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => secondItem.Allowed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => secondItem.Controller)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => secondItem.Passed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => secondItem.Accepted)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

<script>
    document.querySelectorAll(".save-button").forEach(function (button) {
        button.addEventListener("click", function () {
            var rowIndex = this.getAttribute("data-row-index"); // Получаем индекс строки
            var itemId = this.getAttribute("data-item-id"); // Получаем item.Id

            // Выводим индексы для отладки
            console.log("Row Index:", rowIndex);
            console.log("Item Id:", itemId);

            // Получаем значение input для данной строки
            var input = this.closest("tr").querySelector('input[name^="Price"]');
            var inputValue = input ? input.value : null;

            // Выводим значение для отладки
            console.log("Input Value:", inputValue);

            // Если значение input было найдено, отправляем данные на сервер через fetch
            if (inputValue !== null) {
                fetch("/Invoice/AddPriceInvoice", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({ id: itemId, price: inputValue })
                })
                    .then(response => {
                        if (response.ok) {
                            // Обработка успешного ответа от сервера, если необходимо
                        } else {
                            // Обработка ошибки
                        }
                    })
                    .catch(error => {
                        // Обработка ошибки
                    });
            }
        });
    });
</script>

InvoiceAutomation/Views/Invoice/List.cshtml
@model IEnumerable<InvoiceAutomation.Models.Invoice>

@{
    ViewData["Title"] = "GetAllAsync";
}

<style>
    body {
        font-family: Arial, sans-serif; /* Шрифт для всего текста */
        margin: 0; /* Убираем отступы на странице */
        padding: 0; /* Убираем внутренние отступы на странице */
    }

    /* Устанавливаем стили для заголовка h1 */
    h2{
        text-align: center; /* Выравниваем заголовок по центру */
    }

    /* Устанавливаем стили для таблицы */
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        background-color: #fff;
        table-layout: fixed; /* Фиксируем ширину столбцов */
    }

    /* Устанавливаем стили для заголовков таблицы (th) */
    th {
        background-color: #f0f0f0;
        padding: 10px;
        text-align: left;
        white-space: nowrap; /* Запрещаем перенос текста в заголовках */
        font-weight: bold;
    }

    /* Устанавливаем стили для ячеек таблицы (td) */
    td {
        padding: 10px;
        text-align: left;
        white-space: nowrap; /* Запрещаем перенос текста в ячейках */
        overflow: hidden; /* Скрываем содержимое, которое не помещается */
        text-overflow: ellipsis; /* Добавляем многоточие для обрезанного текста */
    }

    /* Устанавливаем стили для строк таблицы (tr) */
    tr:nth-child(even) {
        background-color: #f2f2f2; /* Цвет фона четных строк */
    }

    /* Устанавливаем стили для строк таблицы при наведении курсора */
    tr:hover {
        background-color: #ddd; /* Цвет фона строки при наведении курсора */
    }

    /* Устанавливаем стили для ссылок в ячейках таблицы */
    a {
        text-decoration: none; /* Убираем подчеркивание для ссылок */
        color: #007bff; /* Цвет ссылок */
    }

        /* Устанавливаем стили для ссылок в ячейках таблицы при наведении курсора */
        a:hover {
            text-decoration: underline; /* Подчеркиваем ссылки при наведении курсора */
        }

    .invoiceNumber {
        display: flex;
        align-items: center;
        justify-content: center;
    }

        .invoiceNumber label {
            min-width: 160px;
            font-weight: bold;
        }

        .invoiceNumber input {
            width: 60%;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

    .add-button {
        background-color: #0074d9;
        color: white;
        border: none;
        padding: 8px 16px;
        text-align: center;
        font-size: 14px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    #search-form {
        border-radius: 5px;
        text-align: center;
    }

        #search-form label {
            display: inline-block; /* Добавлено для размещения в одной строке */
            margin-bottom: 10px;
            font-size: 18px; /* Увеличение размера шрифта */
        }

        #search-form input[type="text"] {
            width: 800px; /* Увеличение ширины поля ввода */
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            font-size: 16px; /* Увеличение размера шрифта */
        }

        #search-form input[type="submit"] {
            background-color: #0074d9;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            cursor: pointer;
            font-size: 18px; /* Увеличение размера шрифта */
        }

            #search-form input[type="submit"]:hover {
                background-color: #0056b3;
            }

</style>

 <h2>Работа с накладными</h2>

<form id="search-form" asp-controller="Invoice" asp-action="Search" method="get">
    <div>
        <label>Номер документа:</label>
        <input type="text" name="Invoice_Number" placeholder="Введите строку" />
        <input type="submit" value="Поиск накладной" />
    </div>
</form>

    <form asp-action="List">
    <table class="data-grid">
    <thead>
        <tr>
            <th>
                    <label>Номер докладной</label>
            </th>
            <th>
                <label>№ документа</label>
            </th>
            <th>
                    <label>Дата</label>
            </th>
            <th>
                    <label>Шифр отправителя</label>
            </th>
            <th>
                    <label>Шифр получателя</label>
            </th>
            <th>
                    <label>Разрешил</label>
            </th>
            <th>
                    <label>Контролёр</label>
            </th>
            <th>
                    <label>Сдал</label>
            </th>
            <th>
                    <label>Принял</label>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Invoice_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Document_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data_Of_Creation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sender_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recipient_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Allowed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Controller)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Passed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Accepted)
            </td>
            <td>
                <a asp-controller="Invoice" asp-action="Details" asp-route-invoice_Number="@item.Invoice_Number">Детали</a>
                        <a asp-controller="Invoice" asp-action="Delete" asp-route-invoice_Number="@item.Invoice_Number">Удалить</a>
                        <a asp-controller="Invoice" asp-action="AddPrice" asp-route-invoice_Number="@item.Invoice_Number"></a>
            </td>
        </tr>
}
    </tbody>
</table>
</form>